<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>网站内容管理中心</title>
    <link rel="Stylesheet" type="text/css" href="/public/contents/login.css" />
    <script src="/public/scripts/jquery.js" type="text/javascript"></script>
    <script src="/public/scripts/jquery.base.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {

            $('.textbox').each(function () {
                $(this).bind("focus", function () {
                    $(this).addClass("textcurr");
                });
                $(this).bind("blur", function () {
                    $(this).removeClass("textcurr");
                });
            });

            var err = getUrlParam("err");
            if (err != "") {
                $('#txtLoginName').val(escape(getUrlParam("u")));
                if (err == "code") {
                    $('#error_txtCheckCode').html("* 验证码错误");
                    $('#txtLoginPass').focus();
                } else {
                    $('#error_txtLoginName').html("* 登录失败");
                    $('#txtLoginName').focus();
                }
            }
            else {
                if ($('#txtLoginName').val()) {
                    $('#txtLoginPass').focus();
                } else {
                    $('#txtLoginName').focus();
                }
            }


            $('#btnLogin').click(function () {

                var namebox = $('#txtLoginName');
                if ($.trim(namebox.val()) == "") {
                    $('#error_txtLoginName').html("* 用户名不能为空");
                    namebox.focus();
                    return false;
                } else {
                    $('#error_txtLoginName').html("");
                }

                var passbox = $('#txtLoginPass');
                if ($.trim(passbox.val()) == "") {
                    $('#error_txtLoginPass').html("* 密码不能为空");
                    passbox.focus();
                    return false;
                } else {
                    $('#error_txtLoginPass').html("");
                }

                var codebox = $('#txtCheckCode');
                if ($.trim(codebox.val()) == "") {
                    $('#error_txtCheckCode').html("* 验证码不能为空");
                    codebox.focus();
                    return false;
                } else {
                    $('#error_txtCheckCode').html("");
                }

                return true;
            });

        });
        function error_code() {
            var uname = $.trim($('#txtLoginName').val());
            window.location.href = "login.php?u=" + escape(uname) + "&err=code";
        }
        function error_login() {
            var uname = $.trim($('#txtLoginName').val());
            window.location.href = "login.php?u=" + escape(uname) + "&err=login";
        }
        function fleshVerify(type){ 
        	//重载验证码
        	var timenow = new Date().getTime();
        	if (type){
        		$('#d').attr("src", '/admin_login/captcha/adv/1/'+timenow);
        	}else{
        		$('#d').attr("src", '/admin_login/captcha/'+timenow);
        	}
        }
        $(document).ready(function(){
        	fleshVerify();
        });
    </script>
</head>
<body>
    <form action="/admin_login/check/" method="post">

        <div id="box-login">

            <div class="loginarea clearfix">

                <div class="logininfo">&nbsp;<!--管理登录--></div>

                <div class="loginform">
                    <ul>
                        <li>
                            <div class="left">用户名：</div>
                            <div class="right">
                                <input type="text" class="textbox" name="uname" />
                                <span id="error_txtLoginName" class="text-err"></span>
                            </div>
                        </li>
                        <li>
                            <div class="left">密　码：</div>
                            <div class="right">
                                <input type="password" class="textbox"  name="upass" />
                                <span id="error_txtLoginPass" class="text-err"></span>
                            </div>
                        </li>
                        <li>
                        	<div class="left">验证码：</div>
                        	<div class="right"><input class="textbox" type="text" name="Auth_code" placeholder="输入验证码" value='' data-required="required">
			        		<img id="d" src='' onClick="fleshVerify()" border="0" alt="点击刷新验证码" style="cursor:pointer;vertical-align:middle"/></div>
                        
                        </li>
                  <li></li>
                  <li>
                            <div class="f_button">
                                <button type="submit" class="loginbutton"></button>
                            </div>
                        </li>
                    </ul>
                </div>

            </div>

            <div class="copyright">
                WWW.56CHENG.COM后台管理系统&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;技术：<a href="" target="_blank">Tyrone</a>
            </div>

        </div>

    </form>
</body>
</html>
