<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>业务列表</title>
    <link rel="Stylesheet" type="text/css" href="/public/contents/style.css" />
</head>
<body>
    <div id="wrapper">
        <div id="contain">
	        <table class="table">
	            <tr>
	                <td class="header">业务列表
	                	<span style="float:right; width:200px;font-size:12px;font-weight:100">
	                        <input type="text" class="input" id="keyword" name="keyword" style="width:100px" />&nbsp;&nbsp;
	                        <button type="button" class="button" value="<?php echo $_GET['keyword'];?>" onclick="javascript:window.location.href='/admin_zhangwu/?keyword='+document.getElementById('keyword').value">搜 索</button>
	                    </span>
	                </td>
	            </tr>
	            <tr>
	                <td>
	                
	                    <table class="gridbox">
	                        <tr class="gridtoolbar">
	                            <th> &nbsp; &nbsp; ID</th>
	                            <th> &nbsp; &nbsp; 姓名</th>
	                            <th> &nbsp; &nbsp; 部门</th>
	                            <th> &nbsp; &nbsp; 职位</th>
	                            <th> &nbsp; &nbsp; 操作</th>
	                        </tr>
	                        <?php 
	                        	foreach($content as $value){
	                        		echo "
									<tr height=\"27\">
			                            <td> &nbsp; &nbsp; {$value['id']}</td>
			                            <td> &nbsp; &nbsp; {$value['username']}</td>
			                            <td> &nbsp; &nbsp; {$value['bumen']}</td>
			                            <td> &nbsp; &nbsp; {$value['zhiwei']}</td>
			                            <td> &nbsp; &nbsp; <a href=\"/admin_zhangwu/index/?uid={$value['id']}\" target='_blank'>所有业务</a>&nbsp;<a href=\"/admin_user/edit/id/{$value['id']}\" target='_blank'>修改</a></td>
			                        </tr>";
	                        	}
	                        
	                        ?>
	                        	                        
	                    </table>
	                
	                </td>
	            </tr>
	            <tr>
                    <td class="aspnetPager">
                        <span class="pagermain">
                        	<button type="button" class="button" onclick="javascript:window.location.href='/admin_user/add'">添加业务员</button>
                       	</span>
                    </td>
                </tr>
	            
	        </table>
      	</div>
    </div>
</body>
</html>