<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>账务导入</title>
    <link rel="Stylesheet" type="text/css" href="/public/contents/style.css" />
	<script type="text/javascript" src="/public/scripts/jquery.min.js" ></script>
	<script type="text/javascript" src="/public/scripts/My97DatePicker/WdatePicker.js" ></script>
</head>
<body>
    <div id="wrapper">
        <div id="contain">
			<form action="/admin_zhangwu/daorusave" enctype="multipart/form-data" method="post">
            	<table class="table">
            		<tr>
	                	<td colspan="3" class="header">账务导入</td>
	               	</tr>
                	<tr>
                    	<td width="10%"></td>
                    	<td width="80%" style="text-align:center">选择文件：<input type="file" class="txt_title" name="csvfile" /></td>
                        <td width="10%"></td>
					</tr>
                    <tr>
                        <td colspan="3" style="text-align:center">
                        	<input type="submit" name="submit" value="上传" class="btn btn-green big">
                        </td>
                    </tr>
				</table>
            </form>
      	</div>
    </div>
</body>
</html>