<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title><?php echo $this->layout['meta_title'];?></title>
        <link rel="shortcut icon" type="/public/image/png" href="/public/img/ico.png"/>
        <link rel="icon" type="/public/image/png" href="/public/img/ico.png"/>
        <link rel="apple-touch-icon" href="/public/img/ico.png" />
        <link rel="stylesheet" href="/public/css/styles.css" type="text/css" />
        <link rel="stylesheet" href="/public/css/custom.css" type="text/css" />
        <script type="text/javascript" SRC="/public/js/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" SRC="/public/js/jquery.ui.widget.min.js"></script>
        <script type="text/javascript" SRC="/public/js/jquery.ui.tabs.min.js"></script>
        <!-- jQuery tooltips -->
        <script type="text/javascript" SRC="/public/js/jquery.tipTip.min.js"></script>
        <!-- Superfish navigation -->
        <script type="text/javascript" SRC="/public/js/jquery.superfish.min.js"></script>
        <script type="text/javascript" SRC="/public/js/jquery.supersubs.min.js"></script>
        <!-- jQuery popup box -->
        <script type="text/javascript" SRC="/public/js/jquery.nyroModal.pack.js"></script>        
    </head>
    <body>
<!-- Page content -->
<div id="page">
    <!-- Wrapper -->
    <div class="wrapper" >
        <h3>管理员信息</h3>
        <span class="subtitle">修改管理员信息</span>
        <hr>
        <div id="tabs" class="ui-tabs">
            <div id="tabs-1" class="ui-tabs-panel">
                <form id="admin_user" method="post" action="/admin_admin/editsave">
                    <table class="stylized full">
                        <tr>
                            <td><span class="red">*</span>用户名</td>
                            <td><?php echo $_SESSION['zw_uname'];?></td>
                        </tr>
                        <tr id="bumen">
                            <td><span class="red">*</span>原密码</td>
                            <td><input type="password" class="half" size="28" name="oldupass" /></td>
                        </tr>
                        <tr id="zhiwei">
                            <td><span class="red">*</span>新密码</td>
                            <td><input type="password" class="half" size="28" name="newupass" /></td>
                        </tr>
                        <tr id="sjifen">
                            <td><span class="red">*</span>新密码确认</td>
                            <td><input type="password" class="half" size="28" name="renewupass" /></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><input type="submit" value="保存" class="btn btn-green big"> &nbsp;&nbsp; 
                                <input class="btn" type="reset" value="重置"></td>
                        </tr>
                    </table>
                </form>
            </div>
            <div class="clear">&nbsp;</div>
        </div>
    </div>
    <!-- End of Wrapper -->
</div>
<!-- End of Page content -->
</body>
</html>