<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>产品修改</title>
    <link rel="Stylesheet" type="text/css" href="/public/contents/style.css" />
</head>
<body>
    <div id="wrapper">
        <div id="contain">
			<form id="admin_user" method="post" action="/admin_yewutype/editsave">
            	<input type="hidden" name="id" value="<?php echo $content['id'];?>" />
            	<table class="table">
            		<tr>
	                	<td colspan="2" class="header">产品修改</td>
	               	</tr>
                	<tr>
                    	<td width="12%" style="text-align:right">名称：</td>
                        <td width="88%"><input type="text" class="txt_title" size="28" name="typename" value="<?php echo $content['typename'];?>" /></td>
					</tr>
                    <tr>
                        <td style="text-align:right">价格：</td>
                        <td><input type="text" class="txt_title" size="28" name="jiage" value="<?php echo $content['jiage'];?>"/></td>
                    </tr>
                    <tr>
                        <td colspan="2" style="text-align:center">
                        	<input type="submit" value="修改产品" class="btn btn-green big"> &nbsp;&nbsp; 
                        	<input class="btn" type="reset" value="重置">
                        </td>
                    </tr>
				</table>
            </form>
      	</div>
    </div>
</body>
</html>