<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>管理中心</title>
    <link rel="Stylesheet" type="text/css" href="/public/contents/default.css" />
    <script src="/public/scripts/jquery.js" type="text/javascript"></script>
    <script src="/public/scripts/ManageJS.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(function ($) {
            window.InitHeight = function () {
                var h = document.body.clientHeight;
                if (window.main_height != h) {
                    window.main_height = h;
                    $('#left').height(300);
                    $('#main_right').height(300 - 28);
                    var height = document.body.clientHeight - 60 - 27;
                    $(".main").height(height);
                    $('#left').height(height);
                    $("#main_right").height(height - 28);
                    $(window.frames["main_right"].document).find('[id^="main_right"]').height(height - 5);
                }
            }
            setInterval("InitHeight()", 100)
            var maxW = 190;
            var minW = 12;
            jQuery("#frameBar").click(function () {
                if ($(this).attr("isclose") == "0") {
                    $('#frameLeft').stop(true, false).animate({ left: (minW - maxW) }, 800);
                    $('#frameLeft').parent().width(minW);
                    $(this).removeClass("bar_c");
                    $(this).addClass("bar_o");
                    $(this).attr("isclose", 1);
                } else {
                    $('#frameLeft').stop(true, false).animate({ left: 0 }, 800);
                    $('#frameLeft').parent().width(maxW);
                    $(this).removeClass("bar_o");
                    $(this).addClass("bar_c");
                    $(this).attr("isclose", 0);
                }
            });
			
            setTimeout("onContentLoad();", 10);
            document.onclick = onclickME;
        })
    </script>
    <style type="text/css">
        html, body
        {
            width:100%;
            min-width:1024px;
            height:100%;
        }
    </style>
</head>
<body>
    <!-- header start -->
    <div id="header">
        <div class="toolbar">
            <?php echo $_SESSION['zw_uname'];?> 欢迎您管理员。 <a href="/admin_login/logout/" target="_top">[注销]</a>
        </div>
        <div class="logo">
            <span class="logo_title">56城网站后台管理</span> <span class="logo_info">欢迎加入物流城大家庭</span>
        </div>
        <div class="menu">
        </div>
        <div class="clear">
        </div>
    </div>
    <!-- header end -->
    <!-- main start -->
    <table cellpadding="0" cellspacing="0" summary="Tyrone" class="main">
        <tr>
            <td style="width: 190px">
                <div id="frameLeft" class="t_l">
                    <div class="t_l_c">
                        <iframe frameborder="0" id="left" name="left" scrolling="auto" src="/public/common/tree.html"
                            style="width: 187px; visibility: visible; z-index: 2;" height="100%">浏览器不支持嵌入式框架，或被配置为不显示嵌入式框架。</iframe>
                        <div title="关闭菜单" id="frameBar" isclose="0" class="bar_c">关闭菜单</div>
                    </div>
                </div>
            </td>
            <td class="t_r">
                <table cellpadding="0" cellspacing="0" class="right">
                    <tr>
                        <td>
                            <table cellpadding="0" cellspacing="0" summary="LzTools" class="tool_bar" style="height:0;">
                                <tr>
                                    <td style="width: 2px">
                                    </td>
                                    <td>
                                        <iframe width="100%" height="30" frameborder="0" framespacing="0" marginwidth="0" marginheight="0" scrolling="no" allowtransparency="true" src="/public/common/managemenu.html" name="tabs" id="main_menu"></iframe>
                                            
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td style="height: 100%">
                        <iframe width="100%" height="100%" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" src="about:blank" allowtransparency="true" id="main_right" name="main_right" style="z-index: 2; /*padding-left: 4px; */"></iframe>
                        </td>
                    </tr>
                </table>
            </td>            
        </tr>
    </table>
    <!-- main end -->
    <!-- footer start -->
    <div id="footer">
    </div>
    <!-- footer end -->
    
</body>
</html>
